import Head from 'next/head';
import { ReactNode } from 'react';
import Navbar from './Navbar';
import MobileNavbar from './MobileNavbar';

type Props = {
  children: ReactNode;
};

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Myshop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Navbar />
        <MobileNavbar />
      </header>
      <main className='pt-16'>{children}</main>
      <footer>&copy; My App</footer>
    </>
  );
};

export default Layout;
